# deployment.yaml
# Este es un manifiesto simplificado que utiliza una imagen pública.
# No necesitas construir ninguna imagen de Docker, solo haz commit de este archivo.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  labels:
    app: helloworld
spec:
  # Puedes cambiar este número para probar la sincronización de Argo CD.
  # Por ejemplo, cámbialo a 4, haz commit, y Argo CD creará un nuevo pod.
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        # Esta es una imagen de demostración pública que no requiere construcción.
        # Es un servidor web simple que devuelve información de la petición.
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  # Usamos ClusterIP para exponer el servicio solo dentro del clúster.
  # Para acceder desde fuera, necesitarías un Ingress o cambiar el tipo a NodePort/LoadBalancer.
  type: ClusterIP
  selector:
    # Este selector debe coincidir con las etiquetas de los Pods del Deployment.
    app: helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
